---
name: ci - benchmark

on:
  push:
  workflow_dispatch:
  schedule:
    # 1 time peer week
    # collecting enough data to draw some graphics
    - cron: '0 1 * * 1'
  # push:
  #   branches:
  #     - master

jobs:
  prepare: 
    name: Prepare build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: Node
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          node-version-file: '.nvmrc'
      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare --activate pnpm@latest
      - name: set store
        run: | 
          mkdir ~/.pnpm-store
          pnpm config set store-dir ~/.pnpm-store     
      - name: setup pnpm config registry
        run: pnpm config set registry https://registry.verdaccio.org
      - name: install dependencies
        run: pnpm install
      - name: Cache .pnpm-store
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # tag=v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-              
  benchmark-autocannon:
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        benchmark:
          - info
          # - tarball
        verdaccioVersion:
          - 3.13.1
          - 4.12.2
          - 5.18.0
          - 6.0.0-6-next.51
    name: Benchmark autocannon
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          node-version-file: '.nvmrc'
      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare --activate pnpm@latest
      - uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # tag=v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}   
      - name: install dependencies
        run: pnpm install    
      - name: start registry
        run: ./scripts/benchmark-prepare.sh ${{matrix.verdaccioVersion}}        
      - name: benchmark        
        run: pnpm benchmark:api -v ${{matrix.verdaccioVersion}} -f ${{matrix.benchmark}}       
        shell: bash
        env:
          DEBUG: metrics*
      - uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # tag=v3
        with:
          name: verdaccio-metrics-api
          path: ./api-results-${{matrix.verdaccioVersion}}-${{matrix.benchmark}}.json  
          if-no-files-found: error
          retention-days: 10 
  benchmark:
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        benchmark:
          - info
          # - tarball
        verdaccioVersion:
          # future 6.x (wip)
          # - local (master branch)
          # old versions to compare same test along previous releases
          - 3.13.1
          - 4.12.2
          - 5.18.0
          - 6.0.0-6-next.51
    name: Benchmark hyperfine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          node-version-file: '.nvmrc'
      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare --activate pnpm@latest
      - uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # tag=v3
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}   
      - name: install dependencies
        run: pnpm install
      - name: install hyperfine
        run: |
          wget https://github.com/sharkdp/hyperfine/releases/download/v1.15.0/hyperfine_1.15.0_amd64.deb
          sudo dpkg -i hyperfine_1.15.0_amd64.deb
      - name: start registry
        run: ./scripts/benchmark-prepare.sh ${{matrix.verdaccioVersion}}
      - name: benchmark        
        run: ./scripts/benchmark-run.sh ${{matrix.benchmark}}
        # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell
        shell: bash
      - name: rename
        run: |
         mkdir -v -p ./benchmark_raw/${{github.sha}}
         mv -v ./hyper-results.json ./benchmark_raw/${{github.sha}}/hyper-results-${{matrix.verdaccioVersion}}-${{matrix.benchmark}}.json
      - uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # tag=v3
        with:
          name: verdaccio-metrics
          path: ./benchmark_raw
          if-no-files-found: error
          retention-days: 10    
  save:
    needs: benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: actions/download-artifact@v3
        with:
          # name: verdaccio-metrics
          path: ./${{github.workspace}/benchmark/${{github.sha}}
      - name: Display structure of downloaded files
        run: ls -R          
      # - uses: actions/download-artifact@v3
      #   with:
      #     name: verdaccio-metrics-api
      # - name: Commit & Push changes
      #   uses: actions-js/push@a52398fac807b0c1e5f1492c969b477c8560a0ba # tag=v1.3
      #   with:
      #      github_token: ${{ secrets.GITHUB_TOKEN }}
      #      message: "chore: updated metrics"
      #      branch: main     